# -*- coding: utf-8 -*-
"""Lab1 iml .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JFbdKIco4vkBggEBgkCsDGGbnIJEHQIY
"""

import pandas as pd
import numpy as np

data = pd.read_csv('lab1.csv')

data

instance_space = 2*2*2*1*2*2
instance_space

hypothesis_space = 4*4*4*3*4*4
hypothesis_space

semantically_distinct_hypothesis = (3*3*3*2*3*3)+1
semantically_distinct_hypothesis

concepts = np.array(data)[:, :-1]

concepts

target = np.array(data)[:, -1]

target

def train(con , tar):
  for i,val in enumerate(tar):
    if val == 'yes':
      specific_h = con[i].copy()
      break

  for i,val in enumerate(con):
    if tar[i] == 'yes':
      for x in range(len(specific_h)):
        if val[x] != specific_h[x]:
          specific_h[x] = '?'
        else:
          pass
  return specific_h

print(train(concepts , target))

data = pd.read_csv('buy.csv')

data

instance_space = 2*3*2*2*3
instance_space

hypothesis_space = 4*5*4*4*5
hypothesis_space

semantically_distinct_hypothesis = (3*4*3*3*4)+1
semantically_distinct_hypothesis

concepts = np.array(data)[:, :-1]

concepts

target = np.array(data)[:, -1]

target

def train(con , tar):
  for i,val in enumerate(tar):
    if val == 'yes':
      specific_h = con[i].copy()
      break

  for i,val in enumerate(con):
    if tar[i] == 'yes':
      for x in range(len(specific_h)):
        if val[x] != specific_h[x]:
          specific_h[x] = '?'
        else:
          pass
  return specific_h

print(train(concepts , target))